### ISSUE TITLE
ERROR  Importing directly from a nuxt.config file is not allowed.

### ISSUE THREAD

**Issue by gaetandezeiraud** [initred/nuxt3-tailwindcss3-starter-kit#2]
` ERROR  Importing directly from a nuxt.config file is not allowed. Instead, use runtime config or a module. [importing /nuxt.config.ts from index.html] `

Seems that removed `'./nuxt.config.{js,ts}',` in the tailwind.config.js fix the error.

**Comment by initred** [comment]
Thank you @Brouilles. The error has been corrected. Thank you for registering the issue.

**Comment by andreich1980** [comment]
Thanks a bunch!
